version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: chore
      include: scope

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "develop"
    commit-message:
      prefix: chore
      include: scope
    ignore:
      # 2022-04-23: Ignoring boto3 changes until we need to care about them.
      - dependency-name: "boto3"
    groups:
      boto-typing:
        patterns:
          - "mypy-boto3-*"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "develop"
    commit-message:
      prefix: chore
      include: scope
    allow:
      # Allow updates for AWS CDK
      - dependency-name: "aws-cdk"

  - package-ecosystem: pip
    directory: /benchmark/src/instrumented
    commit-message:
      prefix: chore
      include: scope
    schedule:
      interval: daily

  - package-ecosystem: pip
    directory: /benchmark/src/reference
    commit-message:
      prefix: chore
      include: scope
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /docs
    commit-message:
      prefix: chore
      include: scope
    schedule:
      interval: daily

  - package-ecosystem: pip
    directory: /docs
    commit-message:
      prefix: chore
      include: scope
    schedule:
      interval: daily

  - package-ecosystem: pip
    directory: /examples/event_handler_graphql/src
    commit-message:
      prefix: chore
      include: scope
    schedule:
      interval: daily

  - package-ecosystem: gomod
    directory: /layer/scripts/layer-balancer
    commit-message:
      prefix: chore
      include: scope
    schedule:
      interval: daily
    groups:
      layer-balancer:
        patterns:
          - "*"

  - package-ecosystem: pip
    directory: /tests/performance/data_masking/load_test_data_masking/pt-load-test-stack/function_1024
    schedule:
      interval: daily

  - package-ecosystem: pip
    directory: /tests/performance/data_masking/load_test_data_masking/pt-load-test-stack/function_128
    schedule:
      interval: daily

  - package-ecosystem: pip
    directory: /tests/performance/data_masking/load_test_data_masking/pt-load-test-stack/function_1769
    schedule:
      interval: daily
