name: Release Drafter

# PROCESS
#
# 1. Enumerate all PRs in merged state
# 2. Filter out any PR labeled `skip-changelog`
# 3. Updates or creates a new release in Draft mode

# USAGE
#
# Always run on merged PRs or manually via GitHub UI for debugging purposes.
#
# see .github/release-drafter.yml for configuration

on:
  push:
    branches:
      - develop
  workflow_dispatch:

permissions:
  contents: read

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # create release in draft mode
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@55d479fb1c5bcad5a4f9099a5d9f37c8857b2845 # v2.4.1
        with:
          egress-policy: audit

      - uses: release-drafter/release-drafter@65c5fb495d1e69aa8c08a3317bc44ff8aabe9772 # v5.20.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
